### ISSUE TITLE
Logging handler doesn't correctly format error message

### ISSUE THREAD

**Issue by tremby** [rollbar/pyrollbar#125]
I'm using the Rollbar `logging` framework handler. I noticed that I'm getting a lot of warnings logged from my Django project with the message "Not Found: %s". On looking at the referenced line of Django source, I see that it is

``` python
            logger.warning('Not Found: %s', request.path,
                        extra={
                            'status_code': 404,
                            'request': request
                        })
```

On looking at the [logging docs](https://docs.python.org/3/library/logging.html#logging.debug), I see that that second argument is supposed to be merged in to the first argument. This is what happens by the file logging handler -- my log files show the correct messages ("Not Found: /wp-login.php" for example). I haven't looked at the Rollbar source but it seems to me that this could be a bug there; an incomplete implementation of these logging calls.

**Comment by franciscoruiz** [comment]
Not sure what the rational is, but it's an explicit decision. See https://github.com/rollbar/pyrollbar/blob/master/rollbar/logger.py#L81

**Comment by tremby** [comment]
Interesting. Maybe so that error messages are grouped more? This doesn't seem useful to me, though. "Not found: /login" would be a lot more worrisome than "Not found: /wp-admin"! Hopefully a maintainer will comment.

**Comment by ezarowny** [comment]
Sorry for the delay there. Some of us were at a conference last week. Taking a look a this today.

**Comment by coryvirok** [comment]
I believe the rationale behind this was that doing it this way, (using the format string and not the format**ted** string) causes these log messages to be grouped together in Rollbar. If we used the formatted string all of these log messages would not necessarily be grouped together. More info in this commit message - https://github.com/rollbar/pyrollbar/commit/306fd88cae04bef3c0f84ad4ca84e0a4b78fc2ed

One thing we could do on rollbar.com is to see that there are format vars and display the full message in Rollbar instead of the format string. Would that address your concern?

**Comment by tremby** [comment]
I agree that in certain cases having the errors grouped would be useful, especially where the error message contains something which is different for every single error (a datestamp maybe, or some invalid user input), and they are really all the same issue. But in some cases the same format string could appear for things which are really totally different issues and I'd much rather they were grouped separately.

The issue obviously is that deciding which is which is not something which can be done automatically.

> One thing we could do on rollbar.com is to see that there are format vars and display the full message in Rollbar instead of the format string. Would that address your concern?

I think that would help, yes.

Perhaps while there is only one set of format vars for a given format string the message could always be displayed (and come up in emails) formatted. Then when multiple sets of format vars have been grouped together for a single format string, the unformatted string is shown for the group, but the separate formatted strings are shown for the individual instances.

It would also be useful to have the option to tell Rollbar to split that group by format vars. Or to split out one particular set of format vars to be tracked separately while leaving any other sets tracked as part of the group.

**Comment by srikiraju** [comment]
AFAIK, in cases where there is an traceback, rollbar will merge based on information from that. It should be safe to use `record.getMessage()` in that case. In the case without `exc_info`, merging occurs based on this message, so we can keep the behaviour the same there.

**Comment by ezarowny** [comment]
Ah, ok I see what you mean. The problem here is that Rollbar doesn't update the Item description if an Occurrence comes in with a different description. Knowing this, I think it might be misleading to use the formatted message in the description. A user might mistakenly believe that all Occurrences of an Item representing a Exception would have similar data.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
