### ISSUE TITLE
Is there a Django logging "handler" ala mail_admins?

### ISSUE THREAD

**Issue by palewire** [rollbar/pyrollbar#21]
I would love be able to use a Django logging ["handler"](https://docs.djangoproject.com/en/dev/topics/logging/#id3), ala `mail_admins`, that could catch errors that happen outside of the middleware and ship them to rollbar. My use case are celery job queue tasks that run in the background separate from web requests.

**Comment by tremby** [comment]
Sorry to dig up such an old issue, but I'm not having luck with this.

I was using the middleware but realized I'd like to send any warnings and above which are logged via `logger.warning()` etc to Rollbar as well as uncaught exceptions. That way I can handle unexpected cases so the user doesn't get an error page, but still be notified about them. What's suggested here seemed like a good solution. I'm not sure if the middleware should still be installed, but I'm guessing not: even without it exceptions are going through `logging`, I think, and so a handler for that should do the trick. Please correct me if I'm wrong. I don't want one given exception logged twice if I can avoid it.

I'm still in debug mode at the moment, so I dropped the `filters: ['require_debug_false'],` line from the config above entirely (and also tried using an empty array for it). Other than that my configuration looks almost the same. I have a "rollbar enabled" configuration option in my environment variables, depending on which I run the following code in my settings.py file:

```python
import rollbar
from django.http import Http404

#MIDDLEWARE_CLASSES.append('rollbar.contrib.django.middleware.RollbarNotifierMiddleware')
ROLLBAR = {
    'access_token': os.environ['ROLLBAR_ACCESS_TOKEN'],
    'environment': os.environ['ENVIRONMENT'],
    'root': BASE_DIR,
    'code_version': get_version(),
    'exception_level_filters': [
        (Http404, 'info'),
    ],
}
rollbar.init(**ROLLBAR)
LOGGING['handlers']['rollbar'] = {
    'class': 'rollbar.logger.RollbarHandler',
    'access_token': os.environ['ROLLBAR_ACCESS_TOKEN'],
    'environment': os.environ['ENVIRONMENT'],
    'level': 'WARNING',
}
LOGGING['loggers']['django']['handlers'].append('rollbar')

print(LOGGING)
```

I see what I expect `LOGGING` to be when I start the application.

But then at runtime I do something like

```python
logger = logging.getLogger(__name__)
logger.error("testing logged error")
```

I get an error logged via my other handlers (console and file) but nothing goes to Rollbar. I've also tried `logger.exception(RuntimeError("test exception"))` and I don't get anything in Rollbar then either.

I've also tried without the `ROLLBAR={...}` and `rollbar.init` lines, and I see the same thing. (I see a `WARNING:rollbar:Rollbar already initialized. Ignoring re-init.` line in the log, so Rollbar is definitely initializing, even without those lines, presumably when the handler is set up.)

With the middleware enabled (the `MIDDLEWARE_CLASSES.append` line uncommented) I *do* get uncaught exceptions logged to Rollbar.

Any idea what I'm missing or doing wrong here?

**Comment by tremby** [comment]
I figured out my issue.

First, I was right that if you set up a log handler like this you *do not* need to use the middleware. I didn't try enabling both, but I would assume an uncaught exception would then be logged twice.

The name of the logger matters. With my above configuration I have configured the `'django'` logger to log to console, file, and Rollbar. But I was instantiating a logger with `logging.getLogger(__name__)`, and since the name of my app is not `django` these settings did not apply.

There are many options.

- Do `getLogger('django')`, but then it's not quite as clear which module the message is coming from.
- Rename the logger in the configuration to your app name, and use `getLogger(__name__)`. This works, but now django's own messages (including uncaught exceptions) are no longer sent to Rollbar, since that handler isn't attached to the `django` logger.
- Duplicate the logging configuration for your app's name and `django`.
- Move the logging configuration to `root`. I found this in the [logging docs](https://docs.python.org/3/library/logging.config.html#dictionary-schema-details) -- my configuration no longer has a `loggers` key but `root` instead. The whole thing looks like the following:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG',
        'propagate': True,
    },
}

if os.environ['ROLLBAR_ENABLED'].lower() == 'true':
    import rollbar
    from ciad.version import get_version
    from django.http import Http404

    ROLLBAR = {
        'access_token': os.environ['ROLLBAR_ACCESS_TOKEN'],
        'environment': os.environ['ENVIRONMENT'],
        'root': BASE_DIR,
        'code_version': get_version(),
        'exception_level_filters': [
            (Http404, 'info'),
        ],
    }
    rollbar.init(**ROLLBAR)
    LOGGING['handlers']['rollbar'] = {
        'class': 'rollbar.logger.RollbarHandler',
        'level': 'WARNING',
    }
    LOGGING['root']['handlers'].append('rollbar')
```

This now appears to be working as I want it to.

Note that in the above I conditionally add Rollbar to the logging configuration. The code would be simpler if Rollbar were always to be enabled.

**Comment by ezarowny** [comment]
Ah cool, thanks for reporting your findings @tremby!

**Comment by BossGrand** [comment]
Is it possible to set the user that triggered the log using this?
