### ISSUE TITLE
Integrating Rollbar with AWS Lambda using Chalice

### ISSUE THREAD

**Issue by ajtran** [rollbar/pyrollbar#228]
[USER]:
I read your docs on Python integration, including the special handling for lambda functions. I am using AWS Chalice for my API, and was considering Rollbar for handling exception reporting. Any notes/pointers on how to integrate with this library? It's not obvious as Chalice does not expose the lambda entrypoint.

I can call init() with the blocking handler so any exceptions have time to be sent out. What I’m not clear on is:
- Using Chalice, they handle the main lambda entrypoint, so would I have to put try blocks around every route? That would be really ugly given I have a ton of routes. Other ideas?
- I also can’t use the decorator as I don’t control the entrypoint.

**Comment by rokob** [comment]
There isn't a clear answer here. Reading the Chalice implementation, one thing you could do is monkey patch `__call__` (https://github.com/aws/chalice/blob/master/chalice/app.py#L575) on your app instance. Due to the magicness of `__call__` in Python, I think the following might work:

```python
def patch_call(instance, func):
    class _(type(instance)):
        def __call__(self, *arg, **kwarg):
           old_call = super(type(instance), self).__call__
           return func(old_call, self, *arg, **kwarg)
    instance.__class__ = _

def lambda_wrapper(old_call, s, event, context):
    try:
        result = old_call(s, event, context)
        return rollbar.wait(lambda: result)
    except:
        rollbar.report_exc_info()
        rollbar.wait()
        raise

from chalice import Chalice
app = Chalice(app_name="helloworld")
patch_call(app, lambda_wrapper) 
```

And from there you should be able to use the `app` like the rest of their docs say and get the same functionality as our wrapper. But I haven't tested that.

**Comment by dmulter** [comment]
:-(
