### ISSUE TITLE
Exception in flask view doesn't grab request info

### ISSUE THREAD

**Issue by sbezboro** [rollbar/pyrollbar#23]
Due to a `OperationalError: (OperationalError) (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'")`

caused by https://github.com/sbezboro/standard-web-flask/blob/a269aef3b19dae4a5ab4df68f6bf351a7c410f00/standardweb/views.py#L103

**Comment by rokob** [comment]
I created a minimal Flask app with the same basic structure as the linked example, errors in views capture request info. I am going to guess this is something that has been since in the 4 years since this was created. The code for capturing request info for Flask looks reasonable and works in my test cases.
