### ISSUE TITLE
consistent "connection aborted" exceptions

### ISSUE THREAD

**Issue by kagaram-twilio** [rollbar/pyrollbar#239]
We found over the weekend that a class of errors in our application has been consistently failing to notify Rollbar for several weeks. The only exception we get is "Connection aborted" and "broken pipe". It isn't an intermittent error due to network issues, it happens reliably and only for this one class of errors.

We are using Rollbar through the Python library, and we run on Google App Engine. Here's a stack trace I copied from GAE logs.

[rollbar-error.log](https://github.com/rollbar/pyrollbar/files/1835521/rollbar-error.log)

The App-level exception seems to be:
```
2018-03-19 20:47:29,429 ERROR: Exception: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1MTQ' for key 'PRIMARY'") [SQL: 'INSERT INTO team (id, name, active) VALUES (%(id)s, %(name)s, %(active)s)'] [parameters: {'name': 'platform-base', 'active': True, 'id': '1MTQ'}] [in /opt/jarvis/jarvis/db/juno_update.py:229]
```

Any guidance appreciated on why this seems to fail Rollbar's validation, and on best practices for getting exceptions reliably to Rollbar.

**Comment by rokob** [comment]
For this error, you always get this failure? The log implies that the socket is closed when attempting to send this exception. There are two possibilities that I can think of at first glance.

1) we are using the requests library's session object (http://docs.python-requests.org/en/master/user/advanced/#session-objects) to get persistent connections, so possibly something is breaking with that session somewhere during the lifecycle of your app and then subsequent requests that try to reuse that session get a EPIPE.

2) The Rollbar API has an issue with the payload maybe a 413 because it is too large or there is a rate limit hit so a 429. In any event, the post request can't complete because the API closes the connection early when it decides to return one of these error statuses.

If this particular error generates an item that is too big then maybe (2) is the culprit. Alternatively, if this only happens sometimes, it could be this error is the one that is often at the tail end of a burst of errors which causes a rate limit.

Otherwise, it could just be an issue with the way we are not handling problems with the session getting closed. Let me dig around a little bit and see what I can come up with.

**Comment by kagaram-twilio** [comment]
I was able to confirm that the payload is indeed too large.
