### ISSUE TITLE
Feature request: setting to control inclusion of request in exception payload

### ISSUE THREAD

**Issue by kagaram-twilio** [rollbar/pyrollbar#242]
#239 was caused by the current request containing a large payload. On exceptions in such requests, rollbar.com isn't able to handle this payload. As a result, when things go wrong we get no alerts.

We patched this on our end by forcibly clearing `request.json`. Ideally we'd have a setting for this akin to the `locals={'enabled': False}` argument in `init()`.

**Comment by rivkahstandig3636** [comment]
Good idea!

**Comment by rokob** [comment]
This is odd because by default we have `body.request.json` in the shortener_keys (https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L328,L333) which is intended to reduce the size of the payload by only having a fixed number of key/value pairs. Perhaps this shortener should check the total payload size in addition to the number of elements as somehow this is still causing an issue with your payload. Unless you have some setting that is overriding the use of this shortener.

**Comment by kagaram-twilio** [comment]
We don't override that setting. Our payload has just 8 keys, but the values include large dicts. ¯\_(ツ)_/¯

**Comment by jessicahsieh** [comment]
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/20738850300

**Comment by danielmorell** [comment]
There was a bug in how we applied the shortener to deep objects. This should be resolved by the release of `v1.1.0-alpha`.
