### ISSUE TITLE
Problem with passing access_token to send_payload

### ISSUE THREAD

**Issue by ihoru** [rollbar/pyrollbar#266]
As an example, I'm looking at the code in `_report_exc_info`:
```python
payload = _build_payload(data)
send_payload(payload, data.get('access_token'))
```

Second argument should be access_token which is `None`, but if I change calling to:
```python
send_payload(payload, payload.get('access_token'))
```

everything is going to be all right!

It works so on me local machine, but at the production everything is fine.
I can't what occurs such issue, and why it works at production, because considering the whole code it should not!

`__version__ = '0.14.0'`

**Comment by rokob** [comment]
If you follow that code through, even if the access token is `None` all that happens is that the token will not be put in the header. The token will still be embedded inside the payload object because of the code in `_build_payload`. I think using `data.get('access_token')` was just an oversight and you are right it should be `payload.get(...)`. But the items are still sent fine because the token is still inside the payload.
